[build]
command = "eleventy"
functions = "netlify/functions"
publish = "_site"

[[redirects]]
from = "/data/"
to = "/.netlify/functions/weekly"
status = 200
force = true
_generated_by_eleventy_serverless = "weekly"
